name: NDA
channels:
  - conda-forge
  - defaults
dependencies:
#  - asttokens=2.4.1=pyhd8ed1ab_0
#  - bzip2=1.0.8=h2bbff1b_6
#  - ca-certificates=2024.9.24=haa95532_0
#  - colorama=0.4.6=pyhd8ed1ab_0
#  - comm=0.2.2=pyhd8ed1ab_0
#  - debugpy=1.6.7=py312hd77b12b_0
#  - decorator=5.1.1=pyhd8ed1ab_0
#  - exceptiongroup=1.2.2=pyhd8ed1ab_0
#  - executing=2.1.0=pyhd8ed1ab_0
#  - expat=2.6.3=h5da7b33_0
#  - importlib-metadata=8.5.0=pyha770c72_0
#  - ipykernel=6.29.5=pyh4bbf305_0
#  - jedi=0.19.1=pyhd8ed1ab_0
#  - jupyter_client=8.6.3=pyhd8ed1ab_0
#  - jupyter_core=5.7.2=py312haa95532_0
#  - krb5=1.21.3=hdf4eb48_0
#  - libffi=3.4.4=hd77b12b_1
#  - libsodium=1.0.20=hc70643c_0
#  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
#  - nest-asyncio=1.6.0=pyhd8ed1ab_0
#  - openssl=3.3.2=h2466b09_0
#  - packaging=24.1=pyhd8ed1ab_0
#  - parso=0.8.4=pyhd8ed1ab_0
#  - pickleshare=0.7.5=py_1003
#  - pip=24.2=py312haa95532_0
#  - platformdirs=4.3.6=pyhd8ed1ab_0
#  - prompt-toolkit=3.0.48=pyha770c72_0
#  - psutil=5.9.0=py312h2bbff1b_0
#  - pure_eval=0.2.3=pyhd8ed1ab_0
#  - pygments=2.18.0=pyhd8ed1ab_0
#  - python=3.12.7=h14ffc60_0
#  - pywin32=305=py312h2bbff1b_0
#  - pyzmq=25.1.2=py312hd77b12b_0
#  - setuptools=75.1.0=py312haa95532_0
#  - six=1.16.0=pyh6c4a22f_0
#  - sqlite=3.45.3=h2bbff1b_0
#  - stack_data=0.6.2=pyhd8ed1ab_0
#  - tk=8.6.14=h0416ee5_0
#  - tornado=6.4.1=py312h827c3e9_0
#  - traitlets=5.14.3=pyhd8ed1ab_0
#  - typing_extensions=4.12.2=pyha770c72_0
#  - ucrt=10.0.22621.0=h57928b3_1
#  - vc=14.40=h2eaa2aa_1
#  - vc14_runtime=14.40.33810=hcc2c482_22
#  - vs2015_runtime=14.40.33810=h3bf8584_22
#  - wcwidth=0.2.13=pyhd8ed1ab_0
#  - wheel=0.44.0=py312haa95532_0
#  - xz=5.4.6=h8cc25b3_1
#  - zeromq=4.3.5=ha9f60a1_6
#  - zipp=3.20.2=pyhd8ed1ab_0
#  - zlib=1.2.13=h8cc25b3_1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.8
    # - pywin32=305
  - pyzmq=25.1.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  #- ucrt=10.0.22621.0
  #- vc=14.40
  #- vc14_runtime=14.40.33810
 # - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==3.3.5
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - black==24.8.0
      - bleach==6.1.0
      - boto3==1.35.46
      - botocore==1.35.46
      - build==1.2.2.post1
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - dill==0.3.9
      - distro==1.9.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - docutils==0.21.2
      - eval-type-backport==0.2.0
      - execnet==2.1.1
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.10.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.21.0
      - google-api-python-client==2.149.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-cloud-aiplatform==1.70.0
      - google-cloud-bigquery==3.26.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.5
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-generativeai==0.8.3
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - greenlet==3.1.1
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.67.0
      - grpcio-status==1.67.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.26.1
      - idna==3.10
      - immutabledict==4.2.0
      - importlab==0.8.1
      - iniconfig==2.0.0
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jinja2==3.1.4
      - jiter==0.6.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keyring==25.4.1
      - kiwisolver==1.4.7
      - langchain==0.3.4
      - langchain-community==0.3.3
      - langchain-core==0.3.12
      - langchain-text-splitters==0.3.0
      - langsmith==0.1.137
      - libcst==1.5.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.0
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistralai==1.1.0
      - mistune==3.0.2
      - ml-collections==0.1.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.4.2
      - nh3==0.2.18
      - ninja==1.11.1.1
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - ollama==0.3.3
      - openai==1.52.1
      - orjson==3.10.10
      - overrides==7.7.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - pillow==10.4.0
      - pip-tools==7.4.1
      - pipreqs==0.5.0
      - pkginfo==1.10.0
      - pluggy==1.5.0
      - prometheus-client==0.21.0
      - propcache==0.2.0
      - proto-plus==1.24.0
      - protobuf==5.28.3
      - py==1.11.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycnite==2024.7.31
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.0
      - pydot==3.0.2
      - pyink==24.10.0
      - pylint==3.3.1
      - pyparsing==3.2.0
      - pyproject-hooks==1.2.0
      - pytest==8.3.3
      - pytest-xdist==3.6.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytype==2024.10.11
      - pytz==2024.2
     # - pywin32-ctypes==0.2.3
     # - pywinpty==2.0.14
      - pyyaml==6.0.2
      - reactivex==4.0.4
      - readme-renderer==44.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - retry==0.9.2
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rich==13.9.3
      - rpds-py==0.20.0
      - rsa==4.9
      - s3transfer==0.10.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==3.2.1
      - shapely==2.0.6
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - together==1.3.3
      - tokenizers==0.20.1
      - toml==0.10.2
      - tomlkit==0.13.2
      - torch==2.5.0
      - tqdm==4.66.5
      - transformers==4.45.2
      - twine==5.1.1
      - typer==0.12.5
      - types-python-dateutil==2.9.0.20241003
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - yarg==0.1.9
      - yarl==1.16.0
#prefix: D:\Dennis\miniconda\envs\NDA
